### ISSUE TITLE
Binstall for Cargo Release

### ISSUE THREAD

**Issue by kflansburg** [cargo-bins/release-pr#113]
It looks like `cargo-release` is not packaged for `binstall`, which makes this Action take a long time. Maybe I have something misconfigured.

**Comment by NobodyXu** [comment]
cargo-release does have pre-built binaries for x86_64 macOS, windows and Linux https://github.com/crate-ci/cargo-release/releases

which OS/target are you using?

**Comment by kflansburg** [comment]
We are running in GitHub Actions, I assume the default image x86_64 Linux. Here is the output of the latest run:

https://github.com/cloudflare/workers-rs/actions/runs/8480596847/job/23236592054

And here is the invocation of the install action: https://github.com/cloudflare/workers-rs/actions/runs/8480596847/workflow#L22

Based on the output, I thought that GitHub might be blocking requests for that asset from Actions, but I get a 404 when manually navigating to it as well.

**Comment by kflansburg** [comment]
Looks like the URLs are slightly different:

```
https://github.com/crate-ci/cargo-release/releases/download/0.25.6/cargo-release-v0.25.6-x86_64-unknown-linux-gnu.tar.gz
https://github.com/crate-ci/cargo-release/releases/download/v0.25.6/cargo-release-v0.25.6-x86_64-unknown-linux-gnu.tar.gz
```

One has "v" before the version

**Comment by NobodyXu** [comment]
I think it might be that cargo-binstall has hit the limit of GH API without auth token.

Can you try running `cargo binstall` locally?

If it works fine locally, then you can set env `GITHUB_TOKEN` in CI and it should fix it.

**Comment by kflansburg** [comment]
Ok, makes sense, sorry for the noise.
