### ISSUE TITLE
Support custom options to `cargo release`

### ISSUE THREAD

**Issue by mmagician** [cargo-bins/release-pr#54]
I'd like to be able to use `cargo release` with the `--dependent-version fix` option.

Context: When releasing all crates from a workspace at once (related to https://github.com/cargo-bins/release-pr/issues/53), there are some dependencies between the crates (and circular dev-dependencies, with this [workaround for now](https://github.com/rust-lang/cargo/issues/4242#issuecomment-413193603)), and bumping dependent versions breaks the build. Concrete example: [arkworks-rs/algebra](https://github.com/arkworks-rs/algebra/).

I understand that not all options can be supported, else the action would break, but I think this is an option that shouldn't affect the result.

**Comment by passcod** [comment]
I'd definitely accept a PR for an option to change the value of `--dependent-version`!
