### ISSUE TITLE
Concept of base-branch

### ISSUE THREAD

**Issue by mmagician** [cargo-bins/release-pr#85]
I'm not fully sure I get the idea of `base-branch`.
From the docs I understood that the PR will be done againast `base-branch`.
Example: In my release process, I'd like to make the release PR against a branch called `releases`, and in the second step publish tags & crates from `releases` branch. Therefore, I've set `base-branch: releases`, but either it is not working as expected, or I misunderstood its purpose.
See [this example PR](https://github.com/mmagician/algebra/pull/33), and [the corresponding workflow](https://github.com/mmagician/algebra/blob/master/.github/workflows/release_pr.yml#L35).

**Comment by passcod** [comment]
ohhh that's a bug. your understanding is correct. fix incoming

**Comment by passcod** [comment]
Should be fixed in 2.0.5

**Comment by mmagician** [comment]
Works like a charm: https://github.com/mmagician/algebra/pull/34
Thanks very much!
