### ISSUE TITLE
Use `cargo-semver-checks` to verify the update does not break semver

### ISSUE THREAD

**Issue by NobodyXu** [cargo-bins/release-pr#93]
I'm currently in the process of opening new release prs on cargo-binstall and I just realize that calling `cargo-semver-checks` in release-pr can automate the job of maintaining semver without having to run the command locally or potentially forgetting about this.

**Comment by passcod** [comment]
That's supported already! See https://github.com/cargo-bins/release-pr/blob/main/action.yml#L64
